/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MaritimeRoutesRouteImport } from './routes/maritime-routes'
import { Route as LighthouseNetworkRouteImport } from './routes/lighthouse-network'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AtlasProjectsRouteImport } from './routes/atlas-projects'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JournalIndexRouteImport } from './routes/journal.index'

const MaritimeRoutesRoute = MaritimeRoutesRouteImport.update({
  id: '/maritime-routes',
  path: '/maritime-routes',
  getParentRoute: () => rootRouteImport,
} as any)
const LighthouseNetworkRoute = LighthouseNetworkRouteImport.update({
  id: '/lighthouse-network',
  path: '/lighthouse-network',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasProjectsRoute = AtlasProjectsRouteImport.update({
  id: '/atlas-projects',
  path: '/atlas-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlas-projects': typeof AtlasProjectsRoute
  '/contact': typeof ContactRoute
  '/lighthouse-network': typeof LighthouseNetworkRoute
  '/maritime-routes': typeof MaritimeRoutesRoute
  '/journal/': typeof JournalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlas-projects': typeof AtlasProjectsRoute
  '/contact': typeof ContactRoute
  '/lighthouse-network': typeof LighthouseNetworkRoute
  '/maritime-routes': typeof MaritimeRoutesRoute
  '/journal': typeof JournalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atlas-projects': typeof AtlasProjectsRoute
  '/contact': typeof ContactRoute
  '/lighthouse-network': typeof LighthouseNetworkRoute
  '/maritime-routes': typeof MaritimeRoutesRoute
  '/journal/': typeof JournalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/atlas-projects'
    | '/contact'
    | '/lighthouse-network'
    | '/maritime-routes'
    | '/journal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/atlas-projects'
    | '/contact'
    | '/lighthouse-network'
    | '/maritime-routes'
    | '/journal'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/atlas-projects'
    | '/contact'
    | '/lighthouse-network'
    | '/maritime-routes'
    | '/journal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AtlasProjectsRoute: typeof AtlasProjectsRoute
  ContactRoute: typeof ContactRoute
  LighthouseNetworkRoute: typeof LighthouseNetworkRoute
  MaritimeRoutesRoute: typeof MaritimeRoutesRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/maritime-routes': {
      id: '/maritime-routes'
      path: '/maritime-routes'
      fullPath: '/maritime-routes'
      preLoaderRoute: typeof MaritimeRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lighthouse-network': {
      id: '/lighthouse-network'
      path: '/lighthouse-network'
      fullPath: '/lighthouse-network'
      preLoaderRoute: typeof LighthouseNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas-projects': {
      id: '/atlas-projects'
      path: '/atlas-projects'
      fullPath: '/atlas-projects'
      preLoaderRoute: typeof AtlasProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AtlasProjectsRoute: AtlasProjectsRoute,
  ContactRoute: ContactRoute,
  LighthouseNetworkRoute: LighthouseNetworkRoute,
  MaritimeRoutesRoute: MaritimeRoutesRoute,
  JournalIndexRoute: JournalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
